services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotel_development
    ports:
      - "8081:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  cache:
    image: memcached:latest
    ports:
      - "${CACHE_PORT}:11211"
    command:
      - '--memory-limit=1024'
    volumes: 
      - cache-data:/var/lib/cache/data

volumes:
  postgres_data:
  cache-data:



